[package]
name = "mowtec"
version = "0.1.0"
authors = ["Einar Rosvoll <pigzelner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
byteorder = "1.4.2"
spidev = "0.4.1"
